# Config template for py_ballisticcalc

title = "py_ballisticcalc config"
version = "2.1.0a2"

[pybc.preferred_units]
angular = 'Degree'
distance = 'Meter'
velocity = 'MPS'
pressure = 'hPa'
temperature = 'Celsius'
diameter = 'Centimeter'
length = 'Centimeter'
weight = 'Gram'
adjustment = 'CmPer100m'
drop = 'Centimeter'
energy = 'Joule'
ogw = 'Kilogram'
sight_height = 'Centimeter'
target_height = 'Meter'
twist = 'Centimeter'

#[pybc.calculator]
#max_calc_step_size = { value = 0.5, units = "Foot" }
