# Config template for py_ballisticcalc

title = "py_ballisticcalc config"
version = "2.2.0"

[pybc.preferred_units]
angular = 'Degree'
distance = 'Meter'
velocity = 'MPS'
pressure = 'hPa'
temperature = 'Celsius'
diameter = 'Centimeter'
length = 'Centimeter'
weight = 'Gram'
adjustment = 'Mil'
drop = 'Centimeter'
energy = 'Joule'
ogw = 'Kilogram'
sight_height = 'Centimeter'
target_height = 'Meter'
twist = 'Centimeter'
time = 'Second'
