# These are supported funding model platforms

#github: [o-murphy] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
#patreon: o-murphy
#open_collective: o-murphy # Replace with a single Open Collective username
ko_fi: o_murphy
custom: https://www.paypal.com/donate/?hosted_button_id=45PS4KH4RNXFY
