#!/usr/bin/env python
"""setup.py script for py_ballisticcalc library"""
import os

from setuptools import setup, Extension

try:
    from Cython.Build import cythonize
except ImportError:
    import sys

    # use this command to skip building wheel and compiling modules on unsupported platforms
    # pip install --no-build-isolation --no-binary :all: py-ballisticcalc.exts
    setup()
    sys.exit(0)  # Stop installation

ENABLE_CYTHON_COVERAGE = os.environ.get("CYTHON_COVERAGE", "0").lower() in {"1", "true", "yes", "on"}
ENABLE_CYTHON_SAFETY = os.environ.get("CYTHON_SAFETY", "0").lower() in {"1", "true", "yes", "on"}
# When coverage is requested, force Cython to regenerate C code to avoid stale builds
CYTHON_FORCE_REGEN = os.environ.get("CYTHON_FORCE_REGEN", "0").lower() in {"1", "true", "yes", "on"}

# Important paths
THIS_DIR = os.path.abspath(os.path.dirname(__file__))
REPO_ROOT = os.path.abspath(os.path.join(THIS_DIR, os.pardir))

compiler_directives = {
    "language_level": 3,
    "embedsignature": True,
    "cdivision": True, # use with caution! can affect on "/" operator
    "binding": False,  # Keep as False unless you explicitly want Python-level binding methods
    "c_api_binop_methods": True,
    # Suppress noisy warnings about Python-level names (PreferredUnits, Vector, etc.)
    # that are valid Python imports but flagged by Cython's static analyzer.
    "warn.undeclared": False,
    "warn.unreachable": True,
    "warn.maybe_uninitialized": True,
    # Unused warnings are extremely noisy due to autogenerated pickle/state code; disable them.
    "warn.unused": False,
    "warn.unused_arg": False,
    "warn.multiple_declarators": True,
    "show_performance_hints": True,
    # "emit_code_comments": False
}

# Enable line tracing for Cython coverage when requested
if ENABLE_CYTHON_COVERAGE:
    compiler_directives["linetrace"] = True

# When safety is requested, favor correctness checks over speed
if ENABLE_CYTHON_SAFETY:
    compiler_directives.update({
        "boundscheck": True,
        "wraparound": True,
        "initializedcheck": True,
        "nonecheck": True,
        "cdivision": False,
        "overflowcheck": True,
        "embedsignature": True,
    })

ext_base_dir = 'py_ballisticcalc_exts'

# Define all C source files and their paths
C_SOURCES = {
    'v3d': os.path.join(ext_base_dir, 'src', 'v3d.c'),
    'bclib': os.path.join(ext_base_dir, 'src', 'bclib.c'),
    "bind": os.path.join(ext_base_dir, 'src', 'bind.c'),
    # Add any other C source files here
}

# Define dependencies for each extension as a dictionary
# Keys are extension names (as in extension_names list)
# Values are lists of C source file keys from C_SOURCES that they depend on.
EXTENSION_DEPS = {
    "cy_bindings": ["bclib", "bind"],
    "base_traj_seq": ["v3d"],
    "base_engine": ["v3d", "bclib"],
    "euler_engine": ["v3d", "bclib"],
    "rk4_engine": ["v3d", "bclib"],
    "trajectory_data": ["v3d"], # Needs v3d for vector operations
}


# added 'include' to include_dirs for searching headers ***
include_dirs = [
    os.path.join(THIS_DIR, ext_base_dir),  # For .pxd files
    os.path.join(THIS_DIR, ext_base_dir, 'src'),
    os.path.join(THIS_DIR, ext_base_dir, 'include'),
]

# Initialize extensions list
extensions = []

# Dynamically create extensions for names in extension_names
for name, deps in EXTENSION_DEPS.items():
    # Use subproject-local .pyx paths (these exist during build)
    sources = [os.path.join(ext_base_dir, name + '.pyx')]

    # Add dependent C source files from the EXTENSION_DEPS dictionary
    # Use .get(name, []) to safely get an empty list if an extension has no explicit C dependencies
    for dep_key in deps:
        if dep_key in C_SOURCES:
            sources.append(C_SOURCES[dep_key])
        else:
            print(f"Warning: C source '{dep_key}' not found in C_SOURCES dictionary for extension '{name}'.")


    define_macros = []
    if ENABLE_CYTHON_COVERAGE:
        # Enable tracing in both with-GIL and nogil regions
        define_macros.extend([("CYTHON_TRACE", "1"), ("CYTHON_TRACE_NOGIL", "1")])

    extensions.append(
        Extension(
            'py_ballisticcalc_exts.' + name,
            sources=sources,
            include_dirs=include_dirs,
            define_macros=define_macros,
            # extra_compile_args=["-std=c99"], # Uncomment if needed for specific C standards
            # libraries=['m'] # For Linux/macOS, add 'm' for math functions. For Windows, usually not needed or part of default C runtime.
        )
    )

# Standard cythonize with a clean in-project build dir; annotate only if coverage requested
extensions = cythonize(
    extensions,
    compiler_directives=compiler_directives,
    annotate=True, #ENABLE_CYTHON_COVERAGE, # whether to generate .html annotations
    build_dir=os.path.join(ext_base_dir, 'build'),
    force=ENABLE_CYTHON_COVERAGE or CYTHON_FORCE_REGEN,
)

setup(ext_modules=extensions)
