#!/usr/bin/env python

import sys
import subprocess


# def version_match_check(python_executable):
#     from hooks import version_check
#     version_check.main()


def pytest(python_executable):
    result = subprocess.run([python_executable, "-m", "pytest", "./tests"], capture_output=True)

    if result.returncode != 0:
        # print(result.stdout.decode())
        print("Tests failed. Commit aborted.")
        sys.exit(1)


def mypy(python_executable):
    result = subprocess.run([python_executable, "-m", "mypy", "./py_ballisticcalc"], capture_output=True)

    if result.returncode != 0:
        # print(result.stdout.decode())
        print("Typings error. Commit aborted.")
        sys.exit(1)


def main():
    python_executable = sys.executable

    # version_match_check(python_executable)
    mypy(python_executable)
    pytest(python_executable)

    print("Pre-commit hook passed!")
    sys.exit(0)


if __name__ == "__main__":
    main()
