name: Coverage

on:
  push:
    branches:
      - "master"
    paths:
      - "pyproject.toml"
      - "py_ballisticcalc/**"
      - "tests/**"
      - ".github/workflows/coverage.yml"
  pull_request:
    branches:
      - "*"
    paths:
      - "pyproject.toml"
      - "py_ballisticcalc/**"
      - "tests/**"
      - ".github/workflows/coverage.yml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 # required for setuptools-scm

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.11"
          activate-environment: "true"
          github-token: ${{ github.token }}

      - name: Install the project
        run: uv sync --dev
        shell: bash

      - name: Run coverage
        run: uv run pytest tests --cov=py_ballisticcalc --cov-report=xml --cov-report=html
        shell: bash

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
