name: Upload Python Package to Test PyPI

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  build-deploy:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-13, macos-14 ]

    runs-on: ${{ matrix.os }}
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install build cibuildwheel twine 

      - name: Build pure python package
        run: python -m build

      - name: Build binary python package
        run: |
          cd py_ballisticcalc_exts
          python -m build --sdist --outdir ../dist
          cibuildwheel --output-dir ../dist
          cd ..

      - name: List ./dist
        run: ls ./dist

      - name: Publish package distributions to Test PyPI
        run: |
          python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/* --skip-existing --verbose --non-interactive
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
