name: Pyright typing check

on:
  pull_request:
    branches:
      - "*"
    paths:
      - "pyproject.toml"
      - "py_ballisticcalc/**"
      - "tests/**"
      - "py_ballisticcalc.exts/**"
      - ".github/workflows/pyright.yml"

  push:
    branches:
      - "*"
    paths:
      - "pyproject.toml"
      - "py_ballisticcalc/**"
      - "tests/**"
      - "py_ballisticcalc.exts/**"
      - ".github/workflows/pyright.yml"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 # required for setuptools-scm

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.11"
          github-token: ${{ github.token }}

      - name: Install the project
        run: uv sync --dev
        shell: bash

      - name: Run pyright checks
        run: uv run pyright
        shell: bash
